apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.key }}
