server {
    listen 8080;
    server_tokens off;

    location / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_pass 127.0.0.1:9000;
    }
}
